In [51]:
df = pd.read_excel(open('Tiempos prueba.xlsx','rb'),sheet_name='Hoja1',converters={'n°' :int},index_col=[0])
df

    1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
CT
1    0  23  10  17  12  24  21  16  17  12  24  12  23   9  10
2   14   0  10  17   5  19  25  23  15  10  18  15  18  14  12
3   14   7   0  24  20  16  22  17  21  16  13  13   8  24  18
4    5  20  10   0  16  22  18   8  12   7  10  16  18  12   8
5   13  21   8   8   0   5  12  19  15  11  21   8  20  11  19
6    7   7  12  22  12   0  11   6   9  20   5  15  11  18  21
7   12   5  18  21  21  20   0  23  13   6   6  17  14  19  10
8   18  10   9  17  18  16  16   0  14  17  23  16   8  20  13
9   16  16  22  14  12  13  24  20   0   9  13  24  21   5   9
10  14   6  15  15  18  20  11  19   6   0  11   8  12  16  21
11  12  11  21  19   6  10  17  13   6  12   0  18  23  11  25
12  24  23  12   6  20  23  25  22   7   9  24   0   6  13   9
13  14  11  24   9  23   6  22  13  12  15  10  18   0   7  18
14  19  14  25  16  23  10   6  17  20   8  11  24  19   0   8
15  20   7  21  14  19  21  24  23  14  25   5  18  14   5   0

In [22]:
df[2][1]

lon

23

In [24]:
from docplex.mp.model import Model

mdl=Model('SMP')

In [25]:
#machines
k = [1, 2, 3, 4, 5]

In [47]:
arcos =[(i,j) for i in range (1, len(df)+1) for j in range (1,len(df)+1) if i!=j]

In [48]:
arcos

[(1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 15),
 (2, 1),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (2, 10),
 (2, 11),
 (2, 12),
 (2, 13),
 (2, 14),
 (2, 15),
 (3, 1),
 (3, 2),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (3, 10),
 (3, 11),
 (3, 12),
 (3, 13),
 (3, 14),
 (3, 15),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (4, 10),
 (4, 11),
 (4, 12),
 (4, 13),
 (4, 14),
 (4, 15),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (5, 10),
 (5, 11),
 (5, 12),
 (5, 13),
 (5, 14),
 (5, 15),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 7),
 (6, 8),
 (6, 9),
 (6, 10),
 (6, 11),
 (6, 12),
 (6, 13),
 (6, 14),
 (6, 15),
 (7, 1),
 (7, 2),
 (7, 3),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 8),
 (7, 9),
 (7, 10),
 (7, 11),
 (7, 12),
 (7, 13),
 (7, 14),
 (7, 15),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (8, 5),
 (8, 6),
 (8, 7),
 (8, 9),
 (8, 10),
 (8, 11),
 (8, 12),
 (8, 13),
 (8, 14),
 (8, 15),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4),
 (9, 5),
 (9, 6),
 (9, 7),
 (9, 8),
 (9, 10),
 (9, 11),
 (9, 12),
 (9, 13),
 (9, 14),
 (9, 15),
 (10, 1),
 (10, 2),
 (10, 3),
 (10, 4),
 (10, 5),
 (10, 6),
 (10, 7),
 (10, 8),
 (10, 9),
 (10, 11),
 (10, 12),
 (10, 13),
 (10, 14),
 (10, 15),
 (11, 1),
 (11, 2),
 (11, 3),
 (11, 4),
 (11, 5),
 (11, 6),
 (11, 7),
 (11, 8),
 (11, 9),
 (11, 10),
 (11, 12),
 (11, 13),
 (11, 14),
 (11, 15),
 (12, 1),
 (12, 2),
 (12, 3),
 (12, 4),
 (12, 5),
 (12, 6),
 (12, 7),
 (12, 8),
 (12, 9),
 (12, 10),
 (12, 11),
 (12, 13),
 (12, 14),
 (12, 15),
 (13, 1),
 (13, 2),
 (13, 3),
 (13, 4),
 (13, 5),
 (13, 6),
 (13, 7),
 (13, 8),
 (13, 9),
 (13, 10),
 (13, 11),
 (13, 12),
 (13, 14),
 (13, 15),
 (14, 1),
 (14, 2),
 (14, 3),
 (14, 4),
 (14, 5),
 (14, 6),
 (14, 7),
 (14, 8),
 (14, 9),
 (14, 10),
 (14, 11),
 (14, 12),
 (14, 13),
 (14, 15),
 (15, 1),
 (15, 2),
 (15, 3),
 (15, 4),
 (15, 5),
 (15, 6),
 (15, 7),
 (15, 8),
 (15, 9),
 (15, 10),
 (15, 11),
 (15, 12),
 (15, 13),
 (15, 14)]

In [ ]:
x

In [49]:
x=mdl.integer_var_dict(arcos,name='x')

### Objective function

$Min \; Z= \; \displaystyle\sum_{j=1}^{n}C_{0j}\sum_{k=1}^{N} Ky^{k}_{0j}+\sum_{i=1}^{n}\sum_{j=1, j\neq1}^{n}C_{ij}\sum_{k=1}^{N-1} Ky^{k}_{ij}$

In [55]:
mdl.minimize(mdl.sum(df[0][j] *mdl.sum(k* x[0][j][k] for k in k for j in range(1:len(df)+1))) + mdl.sum(df[i][j] *mdl.sum(k* x[i][j][k] for k in lrange(1:len(df)+1))for i in range(1:len(df)+1) for j in range(1:len(df)+1)))

SyntaxError: invalid syntax (<ipython-input-55-432287ce22ef>, line 1)

$\displaystyle\sum_{k=1}^{N} y^{k}_{0j}+\sum_{k=1}^{N-1}\sum_{i=1, i\neq j}^{n} y^{k}_{ij} = 1$     $\; \; (\forall \;j \; \in \; I)$

$\displaystyle\sum_{j=1}^{N} y^{1}_{0j}+\sum_{i=1}^{n}\sum_{j=1, j\neq i}^{n} y^{1}_{ij} = m$     $\; \; (\forall \;i \; \in \; I)$

$\displaystyle\sum_{k=1}^{N} \sum_{j=1}^{n} y^{k}_{0j}=m $

$\displaystyle y^{k+1}_{0j} +  \sum_{i=1, i\neq j}^{n} y^{k+1}_{ij} = \sum_{i=1, i\neq j}^{n} y^{k}_{ji} $     $\; \; (\forall \;i \; \in \; I ; k=1,2,...,N-2)$

$\displaystyle y^{N}_{0j} = \sum_{i=1, i\neq j}^{n} y^{N-1}_{ji} $     $\; \; (\forall \;j \; \in \; I)$

In [ ]:
# Restricciones:

#1
for j in range(len(df)+1):
    mdl.add_constraint(mdl.sum(x[0][j][k] for k in range(1:len(k)+1))+mdl.sumx(x[i][j][k] for k in range(1:len(k))for i in range(1:len(df)+1) if i!=j) =1)
                      
#2
for i in range(len(df)+1):
    mdl.add_constraint(mdl.sum(x[0][j][1] for j in range(1:len(df)+1))+mdl.sumx(x[i][j][1] for i in range(1:len(df)+1)for j in range(1:len(df)+1) if j!=i) = m)
                        
#3
    mdl.add_constraint(mdl.sumx(x[0][j][k] for k in range(1:len(k)+1)for j in range(1:len(df)+1)) = m)
#4
for k in range(len(k)-1):
    for i in range(len(df)+1):
        mdl.add_constraint(x[0][j][k+1] + mdl.sum(x[i][j][k+1] for j in range(1:len(df)+1) if j!=i)=mdl.sumx(x[j][i][k] for i in range(1:len(df)+1) if i!=j) = m)

#5    
for j in range(len(df)+1):
    mdl.add_constraint(x[0][j][len(k)+1] = mdl.sum(x[j][i][len(k)] for i in range(1:len(df)+1) if i!=j))

In [ ]:
print(mdl.export_to_string())

In [ ]:
#mdl.parameters.timelimit=120
#mdl.parameters.mip.strategy.branch=1
#mdl.parameters.mip.tolerances.mipgap=0.15

solucion = mdl.solve(log_output=True)

In [ ]:
mdl.get_solve_status()

In [ ]:
solucion.display()